<a href="https://colab.research.google.com/github/SHARATHCHINDAM/Deeplearning/blob/main/perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perceptron

importing libraries


In [ ]:
from numpy import array# for array initalisation
from numpy import random# for randomly choosing numbers
from numpy import dot#for doing dot product
from random import choice

activation function


In [ ]:
activationFn=lambda x: 0 if x < 0 else 1 #step activation function if ip is -ve op is 0

Training Dataset

In [ ]:
dataset=[
         (array([0,0,1]),0), #array([x,y,b],e) x,y=input, b=bias, e=expected output to validate
         (array([0,1,1]),1),
         (array([1,0,1]),1),
         (array([1,1,1]),1)
         ]                   # OR gate
print(dataset) 
print(array([0,0,1]),0)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]
[0 0 1] 0


Initializing Random number of Weights 

In [ ]:
weights=random.rand(3)
weights

array([0.79470905, 0.6405252 , 0.55121627])

Initializing Additonal Variables

In [ ]:
r=0.2 #learning rate
n=100 # number of iterations

Training our MOdel

In [ ]:
for j in range(n):
  x, expected=choice(dataset)#random input set, includes repeated numbers
  print(x,expected)
  result=dot(weights,x) #dot product of input and weight vectors
  err = expected-activationFn(result)
  weights += r * err * x #calculate the correction factor, added to weights to improve o/p in n
  #if expected value is bigger, the weights should increased, and vice versa

[0 0 1] 0
[1 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 1 1] 1
[1 0 1] 1
[1 1 1] 1
[0 0 1] 0
[1 0 1] 1
[1 1 1] 1
[0 1 1] 1
[0 1 1] 1
[0 1 1] 1
[1 0 1] 1
[1 1 1] 1
[0 1 1] 1
[1 0 1] 1
[0 1 1] 1
[0 0 1] 0
[0 1 1] 1
[1 0 1] 1
[1 0 1] 1
[0 1 1] 1
[1 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[1 1 1] 1
[1 0 1] 1
[0 1 1] 1
[0 0 1] 0
[0 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 0 1] 1
[1 1 1] 1
[0 0 1] 0
[0 1 1] 1
[0 1 1] 1
[0 0 1] 0
[0 1 1] 1
[1 0 1] 1
[1 0 1] 1
[1 1 1] 1
[1 0 1] 1
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[0 1 1] 1
[0 1 1] 1
[0 0 1] 0
[0 0 1] 0
[1 0 1] 1
[1 1 1] 1
[0 1 1] 1
[0 0 1] 0
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[1 0 1] 1
[0 0 1] 0
[1 1 1] 1
[1 0 1] 1
[0 0 1] 0
[1 1 1] 1
[1 0 1] 1
[0 1 1] 1
[0 0 1] 0
[1 1 1] 1
[0 0 1] 0
[0 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[1 1 1] 1
[1 1 1] 1
[0 1 1] 1
[0 0 1] 0
[1 1 1] 1
[0 1 1] 1
[1 0 1] 1
[1 1 1] 1
[1 0 1] 1
[0 0 1] 0
[0 0 1] 0
[0 0 1] 0
[1 1 1] 1
[0 1 1] 1
[0 0 1] 0
[1 1 1] 1
[0 1 1] 1
[1 1 1] 1
[1 0 1] 1
[0 0 1] 0
[1 0 1] 1
[1 0 1] 1


Evaluating Model

In [ ]:
for x, y in dataset:
  result=dot(x, weights)
  print("Input: {} ResultBeforeActivationFn: {} ResultAfteractivationFn:{}".format(x[:2], round(result,3), activationFn(result)))

Input: [0 0] ResultBeforeActivationFn: -0.049 ResultAfteractivationFn:0
Input: [0 1] ResultBeforeActivationFn: 0.592 ResultAfteractivationFn:1
Input: [1 0] ResultBeforeActivationFn: 0.746 ResultAfteractivationFn:1
Input: [1 1] ResultBeforeActivationFn: 1.386 ResultAfteractivationFn:1
